spring:
  application:
    name: user-thrift-service
  datasource:
    url: jdbc:mysql://localhost:3306/bootu-task
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9701
